# Mandatory settings

name: Math 301 - Advanced Calculus
paginate: 25
paginate_path: "/posts/page/:num/"
url: http://aylvisaker.github.io/MC-MATH301-SP17/
blog_theme: light # Or use dark
baseurl: /MC-MATH301-SP17

# Optional settings

discus_identifier: mc-math301-sp17
ga_analytics: UA-88755650-1
rss_enabled: true
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  flickr: # Add your Flickr handle
  github: aylvisaker
  linkedin: # Add your LinkedIn handle
  twitter: #aylvisaker
  reddit: #aylvisaker
  email: aylvisaker@monmouthcollege.edu
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
